#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2019, FeldHost™ (feldhost.net)                                   #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
# -------------------------------------------------------------------------- #

# snapshot_revert domain name vm_id host

DEPLOY_ID=$1
SNAP_ID=$2
VMID=$3
HOST=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
    DATASTORES=/var/lib/one/datastores
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
    DATASTORES=$ONE_LOCATION/var/datastores
fi

DRIVER_PATH=$(dirname $0)

source $TMCOMMON
source ${DRIVER_PATH}/../../etc/datastore/3par/3par.conf
. ${DRIVER_PATH}/../../datastore/3par/scripts_3par.sh

# get VM state
VM_STATE=`vm_state`

if [ $VM_STATE -ne 8 ] && [ $VM_STATE -ne 9 ]; then
    error_message "Could not revert snapshot if VM state is not POWEROFF or UNDEPLOYED!"
    exit 1
fi

#-------------------------------------------------------------------------------
# Get All VM Images and execute TM snap_revert action
#-------------------------------------------------------------------------------

i=1
while read line
do
    DISK_IDS[$i]="$line"
    (( i++ ))
done < <(onevm show $VMID --all | $GREP -w "DISK_ID" | $CUT -d\" -f2)

REVERT_SCRIPT="${DRIVER_PATH}/../../tm/3par/snap_revert"

for j in `seq 1 ${#DISK_IDS[*]}`; do
    XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

    unset i k XPATH_ELEMENTS

    while IFS= read -r -d '' element; do
        XPATH_ELEMENTS[i++]="$element"
    done < <(onevm show -x $VMID| $XPATH     /VM/TEMPLATE/DISK[DISK_ID=${DISK_IDS[$j]}]/TM_MAD \
                                             /VM/TEMPLATE/DISK[DISK_ID=${DISK_IDS[$j]}]/DISK_ID \
                                             /VM/HISTORY_RECORDS/HISTORY[last\(\)]/DS_ID)

    TM_MAD=${XPATH_ELEMENTS[k++]}
    DISK_ID=${XPATH_ELEMENTS[k++]}
    SYS_DSID=${XPATH_ELEMENTS[k++]}

    if [ "$TM_MAD" = "3par" ]; then
        $REVERT_SCRIPT "${HOST}:${DATASTORES}/${SYS_DSID}/${VMID}/disk.${DISK_ID}" "s${SNAP_ID}" "${VMID}" 0
    fi
done