#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2022, FeldHost™ (feldhost.net)                                   #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
# -------------------------------------------------------------------------- #

# snapshot_revert domain name vm_id host

DEPLOY_ID=$1
SNAP_ID=$2
VMID=$3
HOST=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
    DATASTORES=/var/lib/one/datastores
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
    DATASTORES=$ONE_LOCATION/var/datastores
fi

DRIVER_PATH=$(dirname $0)

source $TMCOMMON
source ${DRIVER_PATH}/../../etc/datastore/3par/3par.conf
. ${DRIVER_PATH}/../../datastore/3par/scripts_3par.sh

#-------------------------------------------------------------------------------
# Get All VM Images and execute TM snap_revert action
#-------------------------------------------------------------------------------

REVERT_SCRIPT="${DRIVER_PATH}/../../tm/3par/snap_revert"

DISK_IDS=$(onevm show $VMID -x | ${DRIVER_PATH}/../../datastore/xpath.rb --stdin '%m%/VM/TEMPLATE/DISK/DISK_ID')

for k in $DISK_IDS; do
    XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

    unset i j XPATH_ELEMENTS

    while IFS= read -r -d '' element; do
        XPATH_ELEMENTS[i++]="$element"
    done < <(onevm show -x $VMID| $XPATH     /VM/TEMPLATE/DISK[DISK_ID=$k]/TM_MAD \
                                             /VM/TEMPLATE/DISK[DISK_ID=$k]/DISK_ID \
                                             /VM/HISTORY_RECORDS/HISTORY[last\(\)]/DS_ID)

    TM_MAD=${XPATH_ELEMENTS[j++]}
    DISK_ID=${XPATH_ELEMENTS[j++]}
    SYS_DSID=${XPATH_ELEMENTS[j++]}

    if [ "$TM_MAD" = "3par" ]; then
        $REVERT_SCRIPT "${HOST}:${DATASTORES}/${SYS_DSID}/${VMID}/disk.${DISK_ID}" "s${SNAP_ID}" "${VMID}" 0
    fi
done