#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2022, FeldHost™ (feldhost.net)                                   #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
# -------------------------------------------------------------------------- #

###############################################################################
# This script is used to copy an image back to its datastore (executed for the saveas operation) 
###############################################################################

# mvds host:remote_system_ds/disk.i fe:SOURCE snapid vmid dsid
#   - fe is the front-end hostname
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - vmid is the id of the VM
#   - dsid is the target datastore (0 is the system datastore)
#   - snapid is the snapshot id. "-1" for none

# ------------ Set up the environment to source common tools ------------

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

. $TMCOMMON

DRIVER_PATH=$(dirname $0)

source ${DRIVER_PATH}/../../etc/datastore/3par/3par.conf
. ${DRIVER_PATH}/../../datastore/3par/scripts_3par.sh

# preserve vars from conf file
CONF_API_ENDPOINT="$API_ENDPOINT"
CONF_IP="$IP"

# -------- Get cpds and datastore arguments from OpenNebula core ------------

SRC=$1
DST=$2
SNAP_ID=$3
VMID=$4
DSID=$5

SRC=`fix_dir_slashes $SRC`
SRC_PATH=`arg_path $SRC`
SRC_HOST=`arg_host $SRC`

#-------------------------------------------------------------------------------
# Get dest ds information
#-------------------------------------------------------------------------------

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onedatastore show -x $DSID | $XPATH \
                    /DATASTORE/TEMPLATE/API_ENDPOINT \
                    /DATASTORE/TEMPLATE/IP \
                    /DATASTORE/TEMPLATE/CPG)

API_ENDPOINT="${XPATH_ELEMENTS[j++]:-$CONF_API_ENDPOINT}"
IP="${XPATH_ELEMENTS[j++]:-$CONF_IP}"
CPG="${XPATH_ELEMENTS[j++]:-$CPG}"

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

DISK_ID=$(basename ${SRC} | cut -d. -f2)

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onevm show -x $VMID| $XPATH \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/IMAGE_ID \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/CLONE \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/DISK_TYPE \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SOURCE \
                    /VM/HISTORY_RECORDS/HISTORY[last\(\)]/DS_ID)

IMAGE_ID="${XPATH_ELEMENTS[j++]}"
CLONE="${XPATH_ELEMENTS[j++]}"
DISK_TYPE="${XPATH_ELEMENTS[j++]}"
IMAGE_NAME_WWN="${XPATH_ELEMENTS[j++]}"
SYS_DSID="${XPATH_ELEMENTS[j++]}"

NAME=$(get_vv_name "$DST")
WWN=$(get_vv_wwn "$DST")

#-------------------------------------------------------------------------------
# Get system ds information
#-------------------------------------------------------------------------------

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onedatastore show -x $SYS_DSID | $XPATH \
                    /DATASTORE/TEMPLATE/API_ENDPOINT \
                    /DATASTORE/TEMPLATE/IP)

SYS_API_ENDPOINT="${XPATH_ELEMENTS[j++]:-$CONF_API_ENDPOINT}"
SYS_IP="${XPATH_ELEMENTS[j++]:-$CONF_IP}"

log "Copy disk id $DISK_ID attached on VM $VMID to new disk $NAME"

# Not clone and not volatile
if [ "$CLONE" == "NO" ] && [ "$DISK_TYPE" == "BLOCK" ]; then
  DISK_ID=$IMAGE_ID
fi

# check IPs of SYSTEM DS and IMAGE DS
if [ "$IP" != "$SYS_IP" ]; then
  log "SYSTEM DS is on remote storage system"

  # Not clone and not volatile
  if [ "$CLONE" == "NO" ] && [ "$DISK_TYPE" == "BLOCK" ]; then
    SRC_WWN=$(get_vv_wwn "$IMAGE_NAME_WWN")
  else
    # get VM disk WWN
    SRC_NAME_WWN=$(get_vm_clone_vv_source "$SYS_API_ENDPOINT" "$SYS_IP" "$VMID" "$DISK_ID")
    SRC_WWN=$(get_vv_wwn "$SRC_NAME_WWN")
  fi

  # export new vv and clone old one to it
  LUN=$(export_vv "$NAME" "$SRC_HOST")
  map_and_copy_to_lun "$SRC_HOST" "$SRC_WWN" "$LUN" "$WWN"

  # unexport new vv
  unmap_lun "$SRC_HOST" "$WWN"
  unexport_vv "$NAME" "$SRC_HOST"
else
  COPY=$(python ${DRIVER_PATH}/../../datastore/3par/3par.py copyVV -a $API_ENDPOINT -i $IP -s $SECURE -u $USERNAME -p $PASSWORD \
                                      -nt $NAMING_TYPE -id $DISK_ID -si $SNAP_ID -vi $VMID -d $NAME -c $CPG -vc $CLONE)

  if [ $? -ne 0 ]; then
    error_message "$COPY"
    exit 1
  fi
fi
