#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2022, FeldHost™ (feldhost.net)                                   #
#                                                                            #
# Portions copyright 2014-2016, Laurent Grawet <dev@grawet.be>               #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
# -------------------------------------------------------------------------- #

# PREMIGRATE SOURCE DST remote_system_dir vmid dsid template
#  - SOURCE is the host where the VM is running
#  - DST is the host where the VM is to be migrated
#  - remote_system_dir is the path for the VM home in the system datastore
#  - vmid is the id of the VM
#  - dsid is the target datastore
#  - template is the template of the VM in XML and base64 encoded

SRC_HOST=$1
DST_HOST=$2

DST_PATH=$3

VMID=$4
DSID=$5

TEMPLATE_64=$(cat)

#--------------------------------------------------------------------------------

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

source $TMCOMMON

DRIVER_PATH=$(dirname $0)

source ${DRIVER_PATH}/../../etc/datastore/3par/3par.conf
. ${DRIVER_PATH}/../../datastore/3par/scripts_3par.sh

#--------------------------------------------------------------------------------

if [ "$SRC_HOST" == "$DST_HOST" ]; then
    log "Not moving $SRC_HOST to $DST_HOST, they are the same host"
    exit 0
fi

#--------------------------------------------------------------------------------

if [ -n "$7" ]; then
    log "Called from tm/$7 but I've nothing to do"
    exit 0
fi

#--------------------------------------------------------------------------------
# Move deployment files to dst host
#--------------------------------------------------------------------------------

DST_PATH_DIRNAME=`dirname $DST_PATH`
DST_PATH_BASENAME=`basename $DST_PATH`

ssh_make_path "$DST_HOST" "$DST_PATH"

log "Moving $SRC_HOST:$DST_PATH to $DST_HOST:$DST_PATH"

ssh_exec_and_log "$DST_HOST" "rm -rf '$DST_PATH'" \
    "Error removing target path to prevent overwrite errors"

TAR_SSH=$(cat <<EOF
set -e -o pipefail
$TAR -C $DST_PATH_DIRNAME --sparse -cf - $DST_PATH_BASENAME | $SSH $DST_HOST '$TAR -C $DST_PATH_DIRNAME --sparse -xf -'
EOF
)

ssh_exec_and_log "$SRC_HOST" "$TAR_SSH" "Error copying disk directory to target host"

#--------------------------------------------------------------------------------
# Discover luns on dst host
#--------------------------------------------------------------------------------

DISK_IDS=$(echo $TEMPLATE_64 | base64 --decode | ${DRIVER_PATH}/../../datastore/xpath.rb --stdin '%m%/VM/TEMPLATE/DISK/DISK_ID')

for k in $DISK_IDS; do
    XPATH="${DRIVER_PATH}/../../datastore/xpath.rb -b $TEMPLATE_64"

    unset i j XPATH_ELEMENTS

    while IFS= read -r -d '' element; do
        XPATH_ELEMENTS[i++]="$element"
    done < <($XPATH     /VM/TEMPLATE/DISK[DISK_ID=$k]/SOURCE \
                        /VM/TEMPLATE/DISK[DISK_ID=$k]/TM_MAD \
                        /VM/TEMPLATE/DISK[DISK_ID=$k]/CLONE \
                        /VM/TEMPLATE/DISK[DISK_ID=$k]/DISK_ID \
                        /VM/TEMPLATE/DISK[DISK_ID=$k]/DISK_TYPE \
                        /VM/TEMPLATE/DISK[DISK_ID=$k]/DATASTORE_ID \
                        /VM/HISTORY_RECORDS/HISTORY[last\(\)]/DS_ID)

    NAME_WWN=${XPATH_ELEMENTS[j++]}
    TM_MAD=${XPATH_ELEMENTS[j++]}
    CLONE=${XPATH_ELEMENTS[j++]}
    DISK_ID=${XPATH_ELEMENTS[j++]}
    DISK_TYPE=${XPATH_ELEMENTS[j++]}
    IMG_DSID=${XPATH_ELEMENTS[j++]}
    SYS_DSID=${XPATH_ELEMENTS[j++]}

    if [ "$TM_MAD" = "3par" ]; then
        # if clone or volatile = non-persistent disk
        if [ "$CLONE" == "YES" ] || [ "$DISK_TYPE" == "FILE" ]; then
          DSID=$SYS_DSID
        else
          DSID=$IMG_DSID
        fi

        #-------------------------------------------------------------------------------
        # Get ds information
        #-------------------------------------------------------------------------------
        XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

        unset i j XPATH_ELEMENTS

        while IFS= read -r -d '' element; do
            XPATH_ELEMENTS[i++]="$element"
        done < <(onedatastore show -x $DSID | $XPATH \
                          /DATASTORE/TEMPLATE/API_ENDPOINT \
                          /DATASTORE/TEMPLATE/IP \
                          /DATASTORE/TEMPLATE/SEC_API_ENDPOINT \
                          /DATASTORE/TEMPLATE/SEC_IP \
                          /DATASTORE/TEMPLATE/REMOTE_COPY \
                          /DATASTORE/TEMPLATE/NAMING_TYPE)

        API_ENDPOINT="${XPATH_ELEMENTS[j++]:-$API_ENDPOINT}"
        IP="${XPATH_ELEMENTS[j++]:-$IP}"
        SEC_API_ENDPOINT="${XPATH_ELEMENTS[j++]:-$SEC_API_ENDPOINT}"
        SEC_IP="${XPATH_ELEMENTS[j++]:-$SEC_IP}"
        REMOTE_COPY="${XPATH_ELEMENTS[j++]:-$REMOTE_COPY}"
        NAMING_TYPE="${XPATH_ELEMENTS[j++]:-$NAMING_TYPE}"

        # if clone or volatile = non-persistent disk
        if [ "$CLONE" == "YES" ] || [ "$DISK_TYPE" == "FILE" ]; then
            # get VM disk WWN
            NAME_WWN=$(python ${DRIVER_PATH}/../../datastore/3par/3par.py getVmClone -a $API_ENDPOINT -i $IP -s $SECURE -u $USERNAME \
                                                                        -p $PASSWORD -nt $NAMING_TYPE -vi $VMID -id $DISK_ID)

            if [ $? -ne 0 ]; then
              error_message "$NAME_WWN"
              exit 1
            fi

            # Disable remote copy for non-persistent disk
            REMOTE_COPY="NO"
        fi

        NAME=$(get_vv_name "$NAME_WWN")
        WWN=$(get_vv_wwn "$NAME_WWN")

        if [ "$REMOTE_COPY" == "YES" ] && [ "$REMOTE_COPY_MODE" == "SYNC" ]; then
            log "Mapping remote $NAME_WWN to $DST_HOST"

            LUN=$(python ${DRIVER_PATH}/../../datastore/3par/3par.py exportVV -a $API_ENDPOINT -i $IP -sapi $SEC_API_ENDPOINT \
                          -sip $SEC_IP -s $SECURE -u $USERNAME -p $PASSWORD -n $NAME -hs $DST_HOST -rc $REMOTE_COPY)

            if [ $? -ne 0 ]; then
              error_message "$LUN"
              exit 1
            fi

            RESCAN_CMD=$(cat <<EOF
                set -e
                $(rescan_scsi_bus "$LUN")
EOF
)

            ssh_exec_and_log "$DST_HOST" "$RESCAN_CMD" \
              "Error registering remote $NAME_WWN to $DST_HOST"
        fi

        log "Mapping $NAME_WWN to $DST_HOST"

        LUN=$(python ${DRIVER_PATH}/../../datastore/3par/3par.py exportVV -a $API_ENDPOINT -i $IP -s $SECURE \
                                                         -u $USERNAME -p $PASSWORD -n $NAME -hs $DST_HOST)

        if [ $? -ne 0 ]; then
          error_message "$LUN"
          exit 1
        fi

        DISCOVER_CMD=$(cat <<EOF
            set -e
            $(discover_lun "$LUN" "$WWN")
EOF
)

        ssh_exec_and_log "$DST_HOST" "$DISCOVER_CMD" \
            "Error registering $NAME_WWN to $DST_HOST"
    fi
done

migrate_other "$@"

exit 0